FROM alpine:3.18

# 1. Accept the build-time argument
ARG BUILD_VERSION

# 2. Intentionally do NOT pass it into an ENV variable.
ENV LIVE_VERSION=""

# 3. Print the text at runtime using the empty environment variable
CMD echo "Running in: Production (Build Ver: ${LIVE_VERSION})"
